# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Login_Scr.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(823, 722)
        MainWindow.setStyleSheet("")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(20, 10, 801, 701))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setGeometry(QtCore.QRect(20, 20, 341, 671))
        self.label.setStyleSheet("background-image: url(:/newPrefix/glass.jpg);\n"
"border-top-left-radius: 50px;")
        self.label.setText("")
        self.label.setObjectName("label")
        self.comboBox = QtWidgets.QComboBox(self.frame)
        self.comboBox.setGeometry(QtCore.QRect(390, 160, 351, 51))
        self.comboBox.setStyleSheet("QComboBox#comboBox{\n"
"    background-color:rgba(0, 0, 0, 0);\n"
"    font: 14pt \"Segoe UI\";\n"
"    color:rgba(0, 0, 0, 0);\n"
"    border: none;\n"
"    border-bottom: 2px solid qlineargradient(spread:pad, x1:0, y1:1, x2:0.970149, y2:0.983, stop:0 rgba(170, 255, 255, 255), stop:1 rgba(255, 255, 255, 255));\n"
"}\n"
"\n"
"")
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.Password = QtWidgets.QLineEdit(self.frame)
        self.Password.setGeometry(QtCore.QRect(390, 230, 351, 51))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.Password.setFont(font)
        self.Password.setStyleSheet("QLineEdit{\n"
"    background-color: rgba(0, 0, 0, 0);\n"
"    font: 14pt \"Segoe UI\";\n"
"    color: rgb(0, 120, 0);\n"
"    border: none;\n"
"    border-bottom: 2px solid qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 rgba(0, 229, 0, 255), stop:1 rgba(0, 121, 0, 255));\n"
"}\n"
"\n"
"QLineEdit:hover{\n"
"    background-color: rgba(0, 0, 42, 80);\n"
"}\n"
"\n"
"")
        self.Password.setEchoMode(QtWidgets.QLineEdit.Password)
        self.Password.setObjectName("Password")
        self.EnterButton = QtWidgets.QPushButton(self.frame)
        self.EnterButton.setGeometry(QtCore.QRect(400, 340, 331, 51))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.EnterButton.setFont(font)
        self.EnterButton.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 rgba(0, 201, 0, 255), stop:1 rgba(25, 81, 36, 255));\n"
"color: rgb(255, 255, 255);\n"
"border-radius: 20px;\n"
"")
        self.EnterButton.setObjectName("EnterButton")
        self.User = QtWidgets.QLineEdit(self.frame)
        self.User.setGeometry(QtCore.QRect(390, 160, 335, 51))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.User.setFont(font)
        self.User.setStyleSheet("QLineEdit{\n"
"    background-color: rgba(0, 0, 0, 0);\n"
"    font: 14pt \"Segoe UI\";\n"
"    color: rgb(0, 120, 0);\n"
"    border: none;\n"
"    border-bottom: 2px solid qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 rgba(0, 229, 0, 255), stop:1 rgba(0, 121, 0, 255));\n"
"}\n"
"\n"
"QLineEdit:hover{\n"
"    background-color: rgba(0, 0, 42, 80);\n"
"}\n"
"\n"
"")
        self.User.setEchoMode(QtWidgets.QLineEdit.Normal)
        self.User.setCursorPosition(0)
        self.User.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.User.setObjectName("User")
        self.label_3 = QtWidgets.QLabel(self.frame)
        self.label_3.setGeometry(QtCore.QRect(20, 20, 341, 671))
        self.label_3.setStyleSheet("background-color: rgba(0, 0, 0, 80);\n"
"border-top-left-radius: 50px;")
        self.label_3.setText("")
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.frame)
        self.label_4.setGeometry(QtCore.QRect(360, 20, 411, 671))
        self.label_4.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0.97, y1:0, x2:0, y2:1, stop:0 rgba(255, 255, 255, 255), stop:0.502488 rgba(199, 255, 254, 242), stop:1 rgba(255, 255, 255, 255));\n"
"border-bottom-right-radius: 50px;")
        self.label_4.setText("")
        self.label_4.setObjectName("label_4")
        self.close_button = QtWidgets.QPushButton(self.frame)
        self.close_button.setGeometry(QtCore.QRect(740, 20, 31, 31))
        self.close_button.setStyleSheet("QPushButton:hover{\n"
"    background-color: rgb(255, 10, 10);\n"
"}\n"
"\n"
"QPushButton{\n"
"    border: none;\n"
"    background-color: rgba(65, 68, 65, 0);\n"
"}")
        self.close_button.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/Green_Icon/Icon_Green/x-square.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.close_button.setIcon(icon)
        self.close_button.setIconSize(QtCore.QSize(32, 30))
        self.close_button.setObjectName("close_button")
        self.BoxButton = QtWidgets.QPushButton(self.frame)
        self.BoxButton.setGeometry(QtCore.QRect(721, 160, 21, 51))
        self.BoxButton.setStyleSheet("QPushButton{\n"
"background-color: qlineargradient(spread:pad, x1:1, y1:1, x2:1, y2:0, stop:0 rgba(191, 191, 191, 255), stop:1 rgba(255, 255, 255, 255));\n"
"    border-radius: 2px;\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: rgb(255, 255, 0);\n"
"}\n"
"QPushButton:pressed{\n"
"    background-color: rgb(255, 85, 0);\n"
"    padding-top: -2px;\n"
"    padding-left: -2px;\n"
"}")
        self.BoxButton.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/Green_Icon/Icon_Green/chevrons-down.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.BoxButton.setIcon(icon1)
        self.BoxButton.setIconSize(QtCore.QSize(30, 30))
        self.BoxButton.setObjectName("BoxButton")
        self.forgot_password = QtWidgets.QPushButton(self.frame)
        self.forgot_password.setGeometry(QtCore.QRect(610, 290, 131, 28))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(9)
        font.setUnderline(True)
        self.forgot_password.setFont(font)
        self.forgot_password.setStyleSheet("QPushButton{\n"
"    color: rgb(0, 120, 0);\n"
"    border: none;\n"
"}\n"
"QPushButton:hover{\n"
"    \n"
"    color: rgb(255, 85, 0);\n"
"}\n"
"")
        self.forgot_password.setObjectName("forgot_password")
        self.label_6 = QtWidgets.QLabel(self.frame)
        self.label_6.setGeometry(QtCore.QRect(-20, 50, 211, 141))
        self.label_6.setStyleSheet("background-image: url(:/newPrefix/278648865_716532036438113_3320425925480882445_n-removebg-preview.png);")
        self.label_6.setText("")
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.frame)
        self.label_7.setGeometry(QtCore.QRect(40, 190, 221, 41))
        self.label_7.setStyleSheet("font: 10pt \"Segoe UI\";\n"
"text-decoration: underline;\n"
"color: rgb(99, 255, 3);")
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.frame)
        self.label_8.setGeometry(QtCore.QRect(40, 230, 261, 31))
        self.label_8.setStyleSheet("font: 10pt \"Segoe UI\";\n"
"text-decoration: underline;\n"
"color: rgb(99, 255, 3);")
        self.label_8.setText("")
        self.label_8.setObjectName("label_8")
        self.Create_account = QtWidgets.QPushButton(self.frame)
        self.Create_account.setGeometry(QtCore.QRect(390, 290, 121, 28))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(9)
        font.setUnderline(True)
        self.Create_account.setFont(font)
        self.Create_account.setStyleSheet("QPushButton{\n"
"    color: rgb(0, 120, 0);\n"
"    border: none;\n"
"}\n"
"QPushButton:hover{\n"
"    \n"
"    color: rgb(255, 85, 0);\n"
"}\n"
"")
        self.Create_account.setObjectName("Create_account")
        self.label_5 = QtWidgets.QLabel(self.frame)
        self.label_5.setGeometry(QtCore.QRect(440, 400, 271, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.label_5.setFont(font)
        self.label_5.setStyleSheet("color: rgba(255, 0, 0, 0);")
        self.label_5.setObjectName("label_5")
        self.eye = QtWidgets.QPushButton(self.frame)
        self.eye.setGeometry(QtCore.QRect(710, 240, 30, 30))
        self.eye.setStyleSheet("QPushButton{\n"
"    background-color: rgba(255, 255, 255, 0);\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color: rgba(0, 10, 10, 80);\n"
"    border-radius: 5px;\n"
"}\n"
"\n"
"QPushButton{\n"
"    border: none;\n"
"    background-color: rgba(65, 68, 65, 0);\n"
"}")
        self.eye.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/Green_Icon/Icon_Green/eye.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.eye.setIcon(icon2)
        self.eye.setIconSize(QtCore.QSize(30, 30))
        self.eye.setObjectName("eye")
        self.frame_2 = QtWidgets.QFrame(self.frame)
        self.frame_2.setGeometry(QtCore.QRect(-120, 440, 321, 291))
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.frame_3 = QtWidgets.QFrame(self.frame)
        self.frame_3.setGeometry(QtCore.QRect(420, 530, 291, 161))
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frame_3)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_9 = QtWidgets.QLabel(self.frame_3)
        font = QtGui.QFont()
        font.setPointSize(7)
        self.label_9.setFont(font)
        self.label_9.setStyleSheet("")
        self.label_9.setObjectName("label_9")
        self.verticalLayout.addWidget(self.label_9, 0, QtCore.Qt.AlignTop)
        self.label_10 = QtWidgets.QLabel(self.frame_3)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_10.setFont(font)
        self.label_10.setStyleSheet("color: rgb(0, 120, 0);\n"
"background-color: rgba(0, 0, 0, 0);")
        self.label_10.setObjectName("label_10")
        self.verticalLayout.addWidget(self.label_10)
        self.label_11 = QtWidgets.QLabel(self.frame_3)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_11.setFont(font)
        self.label_11.setStyleSheet("color: rgb(0, 120, 0);\n"
"background-color: rgba(0, 0, 0, 0);")
        self.label_11.setObjectName("label_11")
        self.verticalLayout.addWidget(self.label_11)
        self.label_12 = QtWidgets.QLabel(self.frame_3)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_12.setFont(font)
        self.label_12.setStyleSheet("color: rgb(0, 120, 0);\n"
"background-color: rgba(0, 0, 0, 0);")
        self.label_12.setObjectName("label_12")
        self.verticalLayout.addWidget(self.label_12)
        self.label_13 = QtWidgets.QLabel(self.frame_3)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_13.setFont(font)
        self.label_13.setStyleSheet("color: rgb(0, 120, 0);\n"
"background-color: rgba(0, 0, 0, 0);")
        self.label_13.setObjectName("label_13")
        self.verticalLayout.addWidget(self.label_13)
        self.pushButton = QtWidgets.QPushButton(self.frame)
        self.pushButton.setGeometry(QtCore.QRect(442, 70, 251, 61))
        font = QtGui.QFont()
        font.setPointSize(24)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton.setFont(font)
        self.pushButton.setStyleSheet("color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 rgba(0, 201, 0, 255), stop:1 rgba(25, 81, 36, 255));\n"
"background-color: rgba(0, 0, 0, 0);")
        self.pushButton.setObjectName("pushButton")
        self.label.raise_()
        self.label_4.raise_()
        self.Password.raise_()
        self.EnterButton.raise_()
        self.comboBox.raise_()
        self.User.raise_()
        self.close_button.raise_()
        self.BoxButton.raise_()
        self.forgot_password.raise_()
        self.label_3.raise_()
        self.label_6.raise_()
        self.label_7.raise_()
        self.label_8.raise_()
        self.Create_account.raise_()
        self.label_5.raise_()
        self.eye.raise_()
        self.frame_2.raise_()
        self.frame_3.raise_()
        self.pushButton.raise_()
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Đăng nhập để sử dụng nhà kính 4 tỷ."))
        self.comboBox.setItemText(0, _translate("MainWindow", "Trần Toàn Thắng"))
        self.comboBox.setItemText(1, _translate("MainWindow", "Đinh Thanh Tùng"))
        self.comboBox.setItemText(2, _translate("MainWindow", "Mai Văn Anh"))
        self.comboBox.setItemText(3, _translate("MainWindow", "Nguyễn Bá Quốc Tài"))
        self.Password.setPlaceholderText(_translate("MainWindow", "Mật khẩu"))
        self.EnterButton.setText(_translate("MainWindow", "OKE"))
        self.User.setPlaceholderText(_translate("MainWindow", "Tên đăng nhập", "10"))
        self.forgot_password.setText(_translate("MainWindow", "Bạn quên mật khẩu"))
        self.label_7.setText(_translate("MainWindow", "Hãy trồng rau"))
        self.Create_account.setText(_translate("MainWindow", "Tạo tài khoản mới"))
        self.label_5.setText(_translate("MainWindow", "Bạn nhập sai mật khẩu."))
        self.label_9.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:12pt; color:#007800;\">Design by: </span><span style=\" font-size:12pt; font-weight:600; color:#007800;\">Tứ Trụ HCMUTE</span></p></body></html>"))
        self.label_10.setText(_translate("MainWindow", "    1. Trần Toàn Thắng 20139015"))
        self.label_11.setText(_translate("MainWindow", "    2. Đinh Thanh Tùng 20139096"))
        self.label_12.setText(_translate("MainWindow", "    3. Mai Văn Anh 20139059"))
        self.label_13.setText(_translate("MainWindow", "    4. Nguyễn Bá Quốc Tài 201390"))
        self.pushButton.setText(_translate("MainWindow", "Đăng Nhập"))
import Icon_rc
import image_main_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
